#! /bin/sh -e

# Take a file that is versioned by bzr and
# add it to baz with the same file-id.

if [ $# -lt 1 ]
then
    echo "usage: $0 FILE" >&2
    exit 1
fi

for f
do
    baz add -i "$( bzr file-id "$f" )" "$f"
done

