.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BZR-BUILDPACKAGE 1 "2007-01-13"
.\" Please adjust this date whenever revising the manpage.
.\"
.SH NAME
bzr-buildpackage \- build a debian package from a bazaar branch
.SH SEE ALSO
.br
Please see the output of bzr-buildpackage --help, and the file
/usr/share/doc/bzr-builddeb/README.gz
