#!/usr/bin/env python

import bzrlib
from bzrlib.plugin import load_plugins
load_plugins ()
from bzrlib.plugins.git.server import BzrBackend
from dulwich.server import UploadPackHandler, serve_command
import sys, os

if len(sys.argv) < 2:
    print "usage: %s <git-dir>" % os.path.basename(sys.argv[0])
    sys.exit(1)

backend = BzrBackend(bzrlib.transport.get_transport("/"))
sys.exit(serve_command(UploadPackHandler, backend=backend))
