#!/usr/bin/env python
# vim: expandtab

# Copyright (C) 2011 Jelmer Vernooij <jelmer@apache.org>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


"""Remote helper for git for accessing bzr repositories."""

CAPABILITIES = ["fetch", "option", "push", "import"]

import optparse
import os
import sys
import bzrlib
bzrlib.initialize()

from bzrlib.plugin import load_plugins
load_plugins()

from bzrlib.controldir import ControlDir
from bzrlib.repository import InterRepository
from bzrlib.transport import get_transport_from_path

from bzrlib.plugins.git.dir import (
    BareLocalGitControlDirFormat,
    LocalGitControlDirFormat,
    )

from bzrlib.plugins.git.object_store import (
    get_object_store,
    )
from bzrlib.plugins.git.refs import (
    BazaarRefsContainer,
    )

options = {}
transports = []

def cmd_capabilities(argv, name, remote_dir):
    sys.stdout.write("\n".join(CAPABILITIES)+"\n\n")
    sys.stdout.flush()


def cmd_list(argv, name, remote_dir):
    repo = remote_dir.find_repository()
    object_store = get_object_store(repo)
    object_store.lock_read()
    try:
        refs = BazaarRefsContainer(remote_dir, object_store)
        for k, v in refs.as_dict().iteritems():
            sys.stdout.write("%s %s\n" % (v, k))
        sys.stdout.write("\n")
    finally:
        object_store.unlock()
    sys.stdout.flush()


def cmd_option(argv, name, remote_dir):
    sys.stdout.write("unsupported\n")
    sys.stdout.flush()


batchcmd = None
wants = []
def cmd_fetch(argv, name, remote_dir):
    global batchcmd, wants
    if batchcmd not in (None, "fetch"):
        raise Exception("fetch command inside other batch command")
    wants.append(tuple(argv[1:]))
    batchcmd = "fetch"


def fetch(wants, shortname, remote_dir, local_dir):
    remote_repo = remote_dir.find_repository()
    local_repo = local_dir.find_repository()
    inter = InterRepository.get(remote_repo, local_repo)
    def update_refs(heads):
        ret = {}
        for (sha1, ref) in wants:
            ret[ref] = (sha1, None)
        return ret
    inter.fetch_refs(update_refs, lossy=False)
    sys.stdout.write("\n")
    sys.stdout.flush()


commands = {
    "capabilities": cmd_capabilities,
    "list": cmd_list,
    "option": cmd_option,
    "fetch": cmd_fetch,
    }

parser = optparse.OptionParser()
(opts, args) = parser.parse_args()
(shortname, url) = args

remote_dir = ControlDir.open(url)

git_path = os.environ["GIT_DIR"]
if git_path.endswith("/.git"):
    git_format = LocalGitControlDirFormat()
    git_path = git_path[:-4]
else:
    git_format = BareLocalGitControlDirFormat()

local_dir = git_format.open(get_transport_from_path(git_path))

while True:
    l = sys.stdin.readline()
    if not l:
        break
    argv = l.strip().split()
    if argv == []:
        if batchcmd == "fetch":
            fetch(wants, shortname, remote_dir, local_dir)
        elif batchcmd is None:
            break
        else:
            raise AssertionError("invalid batch %r" % batchcmd)
        batchcmd = None
    else:
        try:
           commands[argv[0]](argv, shortname, remote_dir)
        except KeyError:
           raise Exception("Unknown remote command %r" % argv)
