#!/usr/bin/env python
import bzrlib
from bzrlib.plugins.git.server import BzrBackend
from dulwich.server import ReceivePackHandler
import sys, os

if len(sys.argv) != 2 or not os.path.isdir(sys.argv[1]):
    print "usage: git-receive-pack <git-dir>"
    sys.exit(1)
 
backend = BzrBackend(sys.argv[1])

def write_fn(data):
    sys.stdout.write(data)
    sys.stdout.flush()

server = ReceivePackHandler(backend, sys.stdin.read, write_fn)
server.handle()
