#!/usr/bin/env python

# Copyright (C) 2011 Jelmer Vernooij <jelmer@apache.org>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


"""Remote helper for git for accessing bzr repositories."""

import optparse
import sys
import bzrlib
bzrlib.initialize()

from bzrlib.plugin import load_plugins
load_plugins()

def cmd_capabilities(argv):
    print

commands = {
    "capabilities": cmd_capabilities,
    }

parser = optparse.OptionParser()
(opts, args) = parser.parse_args()
(shortname, url) = args

while True:
    l = sys.stdin.readline()
    argv = l.strip().split()
    if not argv:
        break
    try:
       commands[argv[0]](argv)
    except KeyError:
       sys.stderr.write("Unknown remote command %r", argv[0])
