#!/usr/bin/env python
import bzrlib
from bzrlib.plugins.git.server import BzrBackend
from dulwich.server import UploadPackHandler
import sys, os, optparse

parser = optparse.OptionParser(usage="usage: git-upload-pack [--strict] [--timeout=nn] <dir>")
parser.add_option("--strict", action="store_true", dest="strict", default=False)
parser.add_option("--timeout", type="int", dest="timeout", default=-1)
options, args = parser.parse_args()

if len(args) != 1 or not os.path.isdir(args[0]):
    print "usage: " + parser.usage
    sys.exit(1)

backend = BzrBackend(sys.argv[1])

def write_fn(data):
    sys.stdout.write(data)
    sys.stdout.flush()

server = UploadPackHandler(backend, sys.stdin.read, write_fn)
server.handle()
