# Copyright (C) 2010 Canonical Limited
# vim: ts=4 sts=4 sw=4
#
# This file is part of bzr-builddeb.
#
# bzr-builddeb is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# bzr-builddeb is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with bzr-builddeb; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

"""Tagging related functions for bzr-builddeb."""

__all__ = ['is_upstream_tag', 'upstream_tag_version']

def is_upstream_tag(tag):
    """Return true if tag is an upstream tag.
    
    :param tag: The string name of the tag.
    :return: True if the tag name is one generated by upstream tag operations.

    >>> is_upstream_tag('2.1')
    False
    >>> is_upstream_tag('upstream-2.1')
    True
    """
    return tag.startswith('upstream-') or tag.startswith('upstream/')


def upstream_tag_version(tag):
    """Return the upstream version portion of an upstream tag name.

    :param tag: The string name of the tag.
    :return: The version portion of the tag.

    >>> upstream_tag_version('upstream-2.1')
    '2.1'
    """
    if tag.startswith('upstream/'):
        return tag[9:]
    segments = tag.split('-')
    segments.reverse()
    while not segments[-1][0].isdigit():
        segments.pop()
    segments.reverse()
    return '-'.join(segments)
