[package]
name = "breezy-patch"
version = { workspace = true }
edition = "2018"
description = "Patch invocation"
license = "GPLv2+"

[lib]

[dependencies]
breezy-osutils = { path = "../osutils" }
tempfile = "3.1.0"
regex = "1.3.9"
lazy_static = "1.4.0"
chrono = { workspace = true }
