#!/usr/bin/env python3

import breezy
import breezy.bzr
import breezy.git
from breezy.git.server import BzrBackend
from dulwich.server import UploadPackHandler, serve_command
import sys, os

if len(sys.argv) < 2:
    print("usage: %s <git-dir>" % os.path.basename(sys.argv[0]))
    sys.exit(1)

backend = BzrBackend(breezy.transport.get_transport("/"))
sys.exit(serve_command(UploadPackHandler, backend=backend))
