#!/bin/sh
python3 /usr/bin/brz selftest -v --parallel=fork --no-plugins -x breezy.tests.test_http.TestBadStatusServer.test_http_get -x breezy.tests.test_http.TestBadStatusServer.test_http_has --load-list python3.passing
