#!/bin/sh

# Disable the doctest breezy.plugins.debian.config.DebBuildConfig.__init__
# as it wants to find sample conf files from the source tree that are not
# guaranteed to actually exist.
/usr/bin/brz selftest -s bp.builddeb --parallel=fork \
    -x breezy.plugins.debian.config.DebBuildConfig.__init__
