[package]
name = "graph-py"
version = { workspace = true }
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"]}
breezy-graph = { path = "../graph", features = ["pyo3"] }
