#!/usr/bin/env python
#
# Call the command line interface for Epydoc.
#

"""Wrapper around Epydoc that just makes it understand bzr's lazy imports."""

# This will enable the lazy_import compatibility code
import bzr_epydoc_uid

from epydoc.cli import cli
cli()


